- [Dependencies](#dependencies)
- [Data](#data)
- [Colonies](#colonies)
- [Populations](#populations)
- [Misc.](#misc)

# Dependencies
```{r}
library(readr)
library(tidyr) # to split line
library(magrittr) # for %>%
library(visreg) # for plotting models
library(multcomp) # for contrasts
library(dplyr) # for summaries to plot
library(plotrix) # for se function
library(cowplot) # ggplot wrapper
```

# Data
```{r}
df1 <- read.csv("o90.csv", skip=11) # skip the comment lines
# line combines multiple factors so separate to get treatment on its own.
df2 <- separate(df1, line, into=c("treatment", "line", "colony"), sep="-", extra="merge")
```

# Colonies

## No. mutations ~ treatment/line
```{r}
# exclude populations - less power to detect variants therefore can't be in the same model as colonies.
# also cannot fit nested model on population - not full rank
df4 <- subset(df2, colony != "P") %>% droplevels
df5 <- data.frame(df4$treatment, df4$line, rowSums(dplyr::select(df4, -ID, -treatment, -line, -colony))) %>% droplevels
colnames(df5) <- c("treatment", "line", "mutations")
#df5$treatment <- relevel(df5$treatment, ref = "WT") # not needed - renamed "WT" to "con"
# note, replace this with a nested model
lm(mutations~treatment/line, data=df5) %>% summary
lm(mutations~treatment/line, data=df5) %>% visreg
# contrast T1 with T1T2
K <- matrix(c(0,1,-1, rep(0, 12)),1)
glht(lm(mutations~treatment/line, data=df5), linfct=K) %>% summary
# sample sizes
table(paste(df5$treatment, df5$line))
df6 <- group_by(df5, treatment)
df6p <- summarise(df6, m_mu=mean(mutations), ci=1.96*std.error(mutations))
# plot mutations by treatment
ggplot(df6p, aes(x=treatment, y=m_mu)) + geom_point(size=5) + geom_errorbar(aes(ymin=m_mu-ci, ymax=m_mu+ci), width=0.2) + ylab("# mutations")
```

```{r, eval=FALSE}
svg("mu_by_tre_col.svg")
ggplot(df6p, aes(x=treatment, y=m_mu)) + geom_point(size=5) + geom_errorbar(aes(ymin=m_mu-ci, ymax=m_mu+ci), width=0.2) + ylab("# mutations")
dev.off()
```

## ~ morphology
```{r}
mf1 <- read_csv("masterCol.csv", skip=5)
mf2 <- subset(mf1, type != "population") %>% droplevels
mf3 <- merge(dplyr::select(mf2, ID, morph), df2, by="ID")
mf4 <- data.frame(dplyr::select(mf3, ID, morph, treatment, line, colony), mutations=rowSums(dplyr::select(mf3, -ID, -morph, -treatment, -line, -colony))) %>% filter(treatment!="ANCESTOR") %>% droplevels
mf5 <- group_by(mf4, treatment, morph) %>% summarize(m_mu=mean(mutations), ci=1.96*std.error(mutations))
ggplot(mf5, aes(x=treatment, y=m_mu, color=morph, group=morph, ymax=5, ymin=1)) + geom_point(size=5, position=position_dodge(width = .5)) + geom_errorbar(aes(ymin=m_mu-ci, ymax=m_mu+ci), width=0.2, position=position_dodge(width = .5)) + ylab("# mutations") + xlab("selection")
```

## *ytr*/*gra* mutations
```{r}
df7 <- data.frame(dplyr::select(df4, treatment, line), ytr=rowSums(select(df4, ytrA, ytrB)), gra=rowSums(select(df4, graS, graR)))
df8 <- group_by(df7, treatment) %>% summarize(f_ytr=sum(ytr)/n(), f_gra=sum(gra)/n()) %>% gather(operon, freq, -treatment)
ggplot(df8, aes(x=treatment, y=freq, fill=operon)) + geom_bar(stat="identity", position="dodge")
```

## growth parameters ~ *ytr*
```{r}
df9 <- data.frame(dplyr::select(df4, ID, treatment, line), ytr=rowSums(select(df4, ytrA, ytrB)), gra=rowSums(select(df4, graS, graR)))
mf6 <- merge(df9, select(mf2, ID, morph, pex, col, mel, vmax, lag, od), by="ID") 
mf6$ytr <- as.factor(mf6$ytr)
glm(vmax~ytr, data=filter(mf6, treatment!="con")) %>% visreg
glm(lag~ytr, data=filter(mf6, treatment!="con")) %>% visreg
glm(od~ytr, data=filter(mf6, treatment!="con")) %>% visreg
```

# Populations
```{r}
df4p <- subset(df2, colony == "P") %>% droplevels
df5p <- data.frame(df4p$treatment, df4p$line, rowSums(dplyr::select(df4p, -ID, -treatment, -line, -colony))) %>% droplevels
colnames(df5p) <- c("treatment", "line", "mutations")
lm(mutations~treatment, data=df5p) %>% summary
lm(mutations~treatment, data=df5p) %>% visreg
# contrast T1 with T1T2
Kp <- matrix(c(0,0,0,-1,1),1)
glht(lm(mutations~treatment, data=df5p), linfct=Kp) %>% summary
# sample sizes
table(df5p$treatment)
df6p <- group_by(df5p, treatment)
df6pp <- summarise(df6p, m_mu=mean(mutations), ci=1.96*std.error(mutations))
# plot mutations by treatment
ggplot(df6pp, aes(x=treatment, y=m_mu)) + geom_point(size=5) + geom_errorbar(aes(ymin=m_mu-ci, ymax=m_mu+ci), width=0.2) + ylab("# mutations")
```

```{r, eval=FALSE}
svg("mu_by_tre_pop.svg")
ggplot(df6pp, aes(x=treatment, y=m_mu)) + geom_point(size=5) + geom_errorbar(aes(ymin=m_mu-ci, ymax=m_mu+ci), width=0.2) + ylab("# mutations")
dev.off()
```

# Misc
172 mutations in 62 strains and then add cnvs
```{r}
# cannot remember why I was excluding thee two mutations from the count
filter(df2, colony!="P") %>% droplevels %>% select(-ywtF.877del, -vraS) %>% gather(gene, mutation, -treatment, -line, -colony, -ID) %>% filter(mutation==1) %>% nrow
filter(df2, colony!="P") %>% droplevels %>% select(-ywtF.877del, -vraS) %>% gather(gene, mutation, -treatment, -line, -colony, -ID) %>% filter(mutation==1) %>% select(ID) %>% unique %>% nrow
dplyr::filter(df2, colony!="P") %>% dplyr::select(ID, treatment, ytrA, ytrB, graS, graR) %>% group_by(ID, treatment) %>% summarize(count = sum(ytrA, ytrB, graS, graR)) %>% dplyr::filter(treatment=="T1T2" | treatment=="T1") %>% as.data.frame
```
